### ISSUE TITLE
页面描述和关键词好像有点小问题呢

### ISSUE THREAD

**Issue by zi-done** [fengkx/hexo-theme-purer#11]
![QQ截图20200901204727.png](https://i.loli.net/2020/09/01/WeBchyKHIs6AEdw.png)
![QQ截图20200901204852.png](https://i.loli.net/2020/09/01/D8Qipqj1zSG5fL7.png)

**Comment by fengkx** [comment]
这两个都不是主题的行为。Hexo在没有tags的时候open_graph helper就会使用keywords。description也是hexo的行为。请仔细阅读Hexo 文档
