### ISSUE TITLE
您好，向您请教几个问题

### ISSUE THREAD

**Issue by kajweb** [fengkx/hexo-theme-purer#12]
抱歉，因为之前没有发现您的主题，我现在用的主题是cofess/hexo-theme-pure，已经差不多改好了，暂时不想折腾了。所以想在现在的基础上优化一下算了。

有几个问题想请教您。
1、代码的highlight主题应该怎么修改？[现在的博客](https://iwwee.com/posts/js_re.html)代码是白底的，如果想换成黑色底的主题，应该在什么地方修改呢？
2、我看您[博客](https://www.fengkx.top)的请求，部分带有Service Worker的标识，请问这样做有什么优势？
3、如果想增加一个**标签云**，会不会很麻烦？

**Comment by fengkx** [comment]
1. 我当初就是改不来才整的这个主题。就是改css，没记错的话具体来说就是`source/css`里的。

2. https://diygod.me/2954

3. https://hexo.io/zh-cn/docs/helpers#tagcloud

**Comment by kajweb** [comment]
Thanks
