### ISSUE TITLE
模版不解析数学公式

### ISSUE THREAD

**Issue by jefferyjob** [fengkx/hexo-theme-purer#19]
您好，安装文档部署后，不解析数学公式，请问是什么原因呢

![image](https://user-images.githubusercontent.com/24731115/142846362-1ab1cb8e-8bed-4234-b9c2-36b854424519.png)

**Comment by jefferyjob** [comment]
请求协助

**Comment by fengkx** [comment]
https://github.com/fengkx/purer-theme-demo/blob/master/source/_posts/Katex-test.md

**Comment by jefferyjob** [comment]
![image](https://user-images.githubusercontent.com/24731115/143159619-805a4087-1a3c-4721-9bb2-f7a64692834a.png)

![image](https://user-images.githubusercontent.com/24731115/143159909-3d434c77-0caf-40d1-a400-240d1c7c970b.png)


还是不解析，数学公式，katex: true 也配置了。。。有点悲伤哦。查看引入也没有问题，就是 hexo g 的时候没有被解析生成，不知道啥情况，没有解析而是原样生成html文本了

`
---
title: Hexo 数学公式支持
toc: true
categories: blog
abbrlink: 712298389
date: 2021-01-21 18:30:41
katex: true
---
`

**Comment by jefferyjob** [comment]
终于搞定了，原来是要吧公式支持的 markdown 配置放到根目录的 _config.yml 。我一直放到模版主题的目录下了，导致无法解析公式。
感谢博主贡献的模版！！！
