### ISSUE TITLE
子目录部署方式后，layout/_partial/post-item-list.ejs href=未用url_for，导致访问404

### ISSUE THREAD

**Issue by chaienda** [fengkx/hexo-theme-purer#3]
![image](https://user-images.githubusercontent.com/20786564/80973853-7cc57800-8e52-11ea-969e-08eb9e507df2.png)
是否是未用url_for 导致的？？

**Comment by chaienda** [comment]
![image](https://user-images.githubusercontent.com/20786564/80979114-89999a00-8e59-11ea-8e90-f97737d1f17a.png)
layout/_common/head.ejs  ${theme.site.favicon} => ${url_for(theme.site.favicon)}

**Comment by itchbelief** [comment]
hexo-generator-json-content  貌似也不支持 子目录的博客，js 去直接加载 url/content.json 不带 root

**Comment by chaienda** [comment]
hexo-generator-json-content 貌似也不支持 子目录的博客，js 去直接加载 url/content.json 不带 root
目录，我通过去改 source/js/search.min.js 的源码解决，fetch("/content.json")  => fetch("/blog/content.json"),    但可以通过配置方式改吗？

**Comment by fengkx** [comment]
子目录的情况没有考虑周到，谢谢指出~

content.json 的路径我先写在了模板里然后js再读取。现在 3785f76d9b2a2427cbcc8b7539747d65c1976d45 路径应该正确了。
