### ISSUE TITLE
disqus not working 

### ISSUE THREAD

**Issue by seungjink** [fengkx/hexo-theme-purer#4]
Commenting with disqus it not working correctly.
It looks that it does not load disqus.ejs file correctly when I generate files.

But I found that if I comment out following two lines in disqus.ejs file, then it works well.

https://github.com/fengkx/hexo-theme-purer/blob/ae07869f5b8eb4f5e39d9df07d79fbce8e0c65dc/layout/_comment/disqus.ejs#L1

https://github.com/fengkx/hexo-theme-purer/blob/ae07869f5b8eb4f5e39d9df07d79fbce8e0c65dc/layout/_comment/disqus.ejs#L16

**Comment by fengkx** [comment]
Thanks, removed 847eb4f
