### ISSUE TITLE
文章界面侧边栏中文无法显示

### ISSUE THREAD

**Issue by NULL-2333** [fengkx/hexo-theme-purer#5]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/20411456/82017214-7c3d9600-9637-11ea-85c0-f45c7d4ba564.png">
但是Home界面的侧边栏是可以正常显示中文的
<img width="456" alt="image" src="https://user-images.githubusercontent.com/20411456/82017262-94151a00-9637-11ea-9c8d-098b9e211b79.png">
因为我没有查询到，所以想问一下这个具体是什么设置

**Comment by fengkx** [comment]
Sidebar 的逻辑在[这里](https://github.com/fengkx/hexo-theme-purer/blob/master/layout/_partial/sidebar-toc.ejs)

toc 生成是使用Hexo自带的helper https://hexo.io/docs/helpers#toc
你可以试着在模板中log看看。

看图片里的是 https://purer.netlify.com 的文档吧，估计跟markdown-it设置有关。或许也可以直接clone https://github.com/fengkx/purer-theme-demo 排除配置的问题。

**Comment by NULL-2333** [comment]
你的这个demo好像有点小问题哎。。我npm run build出来所有的layout都是空的
<img width="620" alt="image" src="https://user-images.githubusercontent.com/20411456/82020439-ece7b100-963d-11ea-8514-c53442c6692b.png">

**Comment by fengkx** [comment]
https://app.netlify.com/sites/purer/deploys/5ebb83b95151d200061b4127
demo 站是自动构建的。demo可以肯定没问题。是不是你忘记pull submodule 了

GitHub Action 的过程更加完整 https://github.com/fengkx/purer-theme-demo/runs/669634842?check_suite_focus=true

**Comment by fengkx** [comment]
尝试复现无果，如果可以的话还请像hexo的issue template那样提供些信息以复现问题。
最好能提供renderer部分的config。
```markdown
**Your site `_config.yml`** (Optional)

**Your theme `_config.yml`** (Optional)

**Hexo and Plugin version(`npm ls --depth 0`)****Your package.json `package.json`**


## Others

<!-- If you have other information. Please write here. -->
```

**Comment by NULL-2333** [comment]
我现在可以了，我重装了一下所有的npm包就好了。
