### ISSUE TITLE
How to custom the size of lines?

### ISSUE THREAD

**Issue by ychen875-usc** [fengkx/hexo-theme-purer#6]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/59945966/82640342-452f2d80-9bbf-11ea-81a3-62ca070b8605.png">

I want to show all posts here, but I found it shows at most 10 posts for a single archive page. I have searched the theme file and cannot find any code that define this limit.

**Comment by fengkx** [comment]
Hexo use [hexo-generator-archive](https://github.com/hexojs/hexo-generator-archive) to generate archive page. change the `per_page` in your site config file.
