### ISSUE TITLE
文档中存在错误

### ISSUE THREAD

**Issue by aimerneige** [fengkx/hexo-theme-purer#8]
[文档](https://purer.netlify.app/document-zh/) 中存在错误

> 支持 emjoi 和 数学公式
> 
> ```bash
> npm i -S markdonw-it-emjoi
> npm i -S @iktakahiro/markdown-it-katex
> ```

应该为

> ```bash
> npm i -S markdown-it-emjoi
> ```

**Comment by fengkx** [comment]
已经更正，谢谢指出。

**Comment by aimerneige** [comment]
后面是 `emoji` 不是 `emjoi`

**Comment by fengkx** [comment]
> 后面是 `emoji` 不是 `emjoi`

已更正，谢谢~
